/*
    *** Tileset.cs ***

    An interface for importing tilesets from the outside world.
*/

using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;
using System.Runtime;
using System.Runtime.CompilerServices;
using System.Threading;
using Carcassonne;
using ExtraMath;
using static System.Math;
using static Carcassonne.GameEngine;
using static Utils;

namespace Carcassonne
{
    ///<Summary>An interface for importing tilesets from the outside world.</Summary>
    public interface ITileset
    {
        bool HasStarter { get; }
        int NPossibleStarters { get; }
        int NPossibleTiles { get; }
        ///<summary>The number of tiles that will be generated by GenerateTiles. Can be less than NPossibleTiles. </summary>
        int NTiles { get; }
        Tile GenerateStarter(RNG rng);
        List<Tile> GenerateTiles(RNG rng);
    }
}
